### PR TITLE
Happy-thoughts-by-axel

### PR DESCRIPTION
**Pull request by AHPIXI**
## Netlify link
Add your Netlify link here.
https://mellow-bienenstitch-6844b1.netlify.app/

### CODE REVIEW

**Comment by AntonellaMorittu** [comment]
hey Axel, the link is not working, please check your deployed app link 👍

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
hey Axel, the link is the same as your happy-thoughts-api app, they should be different. Please check which one belongs to this repo and update the PR descriptions, thank you!

**Comment by AHPIXI** [comment]
> https://mellow-bienenstitch-6844b1.netlify.app/
This is the correct link

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Axel, there is a bug when submitting a thought, the app goes blank page.
<img width="688" alt="Screenshot 2024-06-24 at 15 38 38" src="https://github.com/Technigo/project-happy-thoughts-vite/assets/33493978/5a4dea9d-f36f-4b84-8e12-4821e4a604aa"

Also the like message heart button functionality doesn't work, please give it another take 🙏

**Review by AntonellaMorittu — APPROVED** [review]

**Pull request closed without merging**
